using System;

namespace Battleship2D.Game.Economy;
//class to manage player's credits and spending in the economy system
public class PlayerEconomy
{
    //initial credits for the player, can be modified by game events
    public int Credits { get; set; }
    //total amount spent by the player in the current round, used to calculate remaining credits
    public int Spent { get; set; }
    //income generated by the player for each successful hit in the current round
    public int RoundIncomeOnHit { get; set; } = 10;
    //remaining credits available for the player to spend, calculated as total credits minus spent amount
    public int Remaining => Credits - Spent;
    //constructor to initialize the player's economy with a starting budget
    public void AddCredit(int amount)
    {
        if (amount < 0) throw new ArgumentException("Credits cannot be negative");
        Credits += amount;
    }
    //method to check if the player has enough credits to spend a certain amount
    public bool CanSpend(int amount) => Remaining >= amount;
    //method to spend credits, throws an exception if the player does not have enough credits
    public void Spend(int amount)
    {
        if (!CanSpend(amount)) throw new InvalidOperationException($"Insufficient credits: need {amount}, have {Remaining}");
        Spent += amount;
    }
    //method to refund credits, ensuring that the spent amount does not go below zero
    public void Refund(int amount)
    {
        Spent = Math.Max(0, Spent - amount);
    }
    //method to reset the player's economy for a new round, optionally setting a new starting budget
    public void Reset(int startBudget = 100)
    {
        Credits = startBudget;
        Spent = 0;
    }
}